name: Release

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: ./.github/actions/release
        id: getReleaseTag
        env:
          GITHUB_TOKEN: ${{ secrets.APP_GITHUB_TOKEN }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
